---
name: Release published

on:
  release:
    types: [ published, edited ]

permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  issues: write
  discussions: write
  packages: read
  pages: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]

    name: PHP ${{ matrix.php }} Test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, xdebug
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get Composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: PHPUnit tests with coverage
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Run PHPStan
        run: ./vendor/bin/phpstan

      - name: Run codecov
        uses: codecov/codecov-action@v1

      - name: Check code coverage threshold
        run: |
          min_coverage=80
          coverage=$(php -r "echo simplexml_load_file('coverage.xml')->project->metrics['elements'] > 0 ? (simplexml_load_file('coverage.xml')->project->metrics['coveredelements'] / simplexml_load_file('coverage.xml')->project->metrics['elements'] * 100) : 0;")
          echo "Coverage: $coverage%"
          if (( $(echo "$coverage < $min_coverage" | bc -l) )); then
            echo "Code coverage is below $min_coverage%. Failing the build."
            exit 1
          fi