name: Release Action

on:
  release:
    types:
      - published

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_COMMIT }}

jobs:
  notify-release:
    runs-on: ubuntu-latest
    name: Notify Release
    strategy:
      matrix:
        url: [SLACK_WEBHOOK_ASK_DEVREL_URL, SLACK_WEBHOOK_DEVREL_TOOLING_URL, SLACK_WEBHOOK_DEVREL_PRIVATE_URL, SLACK_WEBHOOK_COMMUNITY]
    steps:
      - name: Send to slack channles
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets[matrix.url]}}
          webhook-type: incoming-webhook
          errors: true
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":initial_external_notification_sent: :php: Version ${{ github.event.release.name }} of the PHP SDK has been released"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ github.event.release.body }}"
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "You can view the full change log <${{github.event.release.html_url }}|here>"
